# Generated by Django 2.2.1 on 2019-09-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogi_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_password',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
