# Generated by Django 3.0.1 on 2019-12-26 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yogi_web', '0002_server_server_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tag',
            new_name='_tag',
        ),
        migrations.AddField(
            model_name='match',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='_name',
            field=models.CharField(db_column='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='_tag',
            field=models.CharField(blank=True, db_column='tag', max_length=10, null=True),
        ),
    ]
